metadata:
  name: "guestbook-ui"
apiVersion: "apps/v1"
kind: "Deployment"
asset_id: "a7f220a6d8bd2be3c27caa411f341c358b3fd056"
spec:
  template:
    metadata:
      labels:
        app: "guestbook-ui"
    spec:
      containers:
      - image: "gcr.io/heptio-images/ks-guestbook-demo:0.2"
        name: "guestbook-ui"
        ports:
        - containerPort: 80
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: "guestbook-ui"
