pr-commit-sha: "5ccaaf8c664fb51d2af442029193713fb18cf0e4"
metadata:
  name: "guestbook-ui"
  labels:
    pr-commit-sha: "ae28cad115834397d6fc107be21cfe58216e1fa7"
apiVersion: "apps/v1"
kind: "Deployment"
spec:
  template:
    metadata:
      labels:
        app: "guestbook-ui"
    spec:
      containers:
      - image: "gcr.io/heptio-images/ks-guestbook-demo:0.2"
        name: "guestbook-ui"
        ports:
        - containerPort: 80
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: "guestbook-ui"
